source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem "compass", "~> 0.12.2"
gem "bootstrap-sass", "~> 2.3.0.0"
gem 'mysql2'


group :development do
  gem 'sqlite3', '1.3.5'
end


group :development, :test do
  gem "rspec-rails", ">= 2.0.1"
  gem 'database_cleaner'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem "bootstrap-sass", "~> 2.3.0.0"
  gem 'coffee-rails', '3.2.2'
  gem 'sass-rails', '3.2.4'
  gem 'uglifier', '1.2.3'
end

gem 'jquery-rails'

group :production do
  gem 'pg', '0.12.2'
end

# add to end of Gemfile
group :test, :development do
  gem 'cucumber-rails'
  gem 'cucumber-rails-training-wheels' # some pre-fabbed step definitions
  gem 'database_cleaner' # to clear Cucumber's test database between runs
  gem 'capybara'         # lets Cucumber pretend to be a web browser
  gem 'launchy'          # a useful debugging aid for user stories
  gem 'cucumber'
end

gem 'paperclip'


